const productsMen = [
  {
    id: 1,
    brand: "Nike",
    title: "Air Max 90s",
    img: "img/airmax90.webp",
    price: 95,
  },
  {
    id: 2,
    brand: "Nike",
    title: "Jordan 1 High",
    img: "img/jordan1.webp",
    price: 100,
  },
  {
    id: 3,
    brand: "Nike",
    title: "Air Max Pulse",
    img: "img/airmaxpulse.webp",
    price: 150,
  },
  {
    id: 4,
    brand: "Nike",
    title: "Air Max Pre Day",
    img: "img/airmaxpre.webp",
    price: 80,
  },
  {
    id: 5,
    brand: "Adidas",
    title: "Ultraboost Running",
    img: "img/ultra.webp",
    price: 150,
  },
  {
    id: 6,
    brand: "Adidas",
    title: "NMD Primeblue",
    img: "img/adidasprime.webp",
    price: 150,
  },
  {
    id: 7,
    brand: "Adidas",
    title: "Grand Court",
    img: "img/grand.webp",
    price: 70,
  },

  {
    id: 8,
    brand: "New Balance",
    img: "img/nb.webp",
    title: "Fresh Foam",
    price: 160,
  },
];

let productsWomen = [
  {
    id: 9,
    brand: "Nike",
    title: "Pegasus",
    img: "img/pegasus.webp",
    price: "130",
  },
  {
    id: 10,
    brand: "Nike",
    title: "Court Legacy",
    img: "img/court.webp",
    price: "90",
  },
  {
    id: 11,
    brand: "Nike",
    title: "Air Max 270",
    img: "img/270.webp",
    price: "160",
  },
  {
    id: 12,
    brand: "Nike",
    title: "Air Force 1 '0",
    img: "img/airforce.webp",
    price: "80",
  },
  {
    id: 13,
    brand: "Adidas",
    title: "Grand Court",
    img: "img/court75.webp",
    price: "75",
  },
  {
    id: 14,
    brand: "New Balance",
    img: "img/nb.webp",
    title: "Fresh Foam",
    price: "160",
  },
  {
    id: 15,
    brand: "Adidas",
    title: "Stan Smith",
    img: "img/stansmith.webp",
    price: "100",
  },
  {
    id: 16,
    brand: "Adidas",
    title: "NMD Primeblue",
    img: "img/adidasprime.webp",
    price: "150",
  },
];

let saleProducts = [
  {
    id: 17,
    brand: "Adidas",
    title: "Gazelle Bold",
    img: "img/gazelle.jpeg",
    price: "50",
  },
  {
    id: 18,
    brand: "Adidas",
    title: "Lite Racer 4.0",
    img: "img/literacer.webp",
    price: "65",
  },
  {
    id: 19,
    brand: "Adidas",
    title: "Kaptir 2.0",
    img: "img/kaptir2.webp",
    price: "60",
  },
  {
    id: 20,
    brand: "Adidas",
    title: "3MC Shoe",
    img: "img/3mc.webp",
    price: "50",
  },
  {
    id: 21,
    brand: "Nike",
    title: "ZOOM",
    img: "img/zoom.webp",
    price: "50",
  },
  {
    id: 22,
    brand: "Nike",
    title: "Off Court",
    img: "img/offcourt.webp",
    price: "50",
  },
  {
    id: 23,
    brand: "Nike",
    title: "Jordan 5",
    img: "img/jordan5.webp",
    price: "50",
  },
  {
    id: 24,
    brand: "Nike",
    title: "Air VaporMax",
    img: "img/airvapormax.webp",
    price: "50",
  },
];
